### ISSUE TITLE
Support images in foot

### ISSUE THREAD

**Issue by Mrfiregem** [swsnr/mdcat#196]
Foot supports viewing images using sixel. It would be nice if mdcat was able to print images to the terminal like it does for others.

**Comment by lunaryorn** [comment]
Please do open a pull request. I don't use this terminal and will not add this myself.

**Comment by swsnr** [comment]
You'd need to get it build on all platforms I build on github actions, without excessive conditional compilation, and you'd need to somehow demonstrate its safety. What the latter means in detail is probably up for discussion, but it would imply that the C library is well established, well tested, and fuzzed, and that the Rust bindings have a good safety policy (eg something along the lines of [ub-risk-2](https://github.com/google/rust-crate-audits#ub-risk-2)).

You'd need to demonstrate all this explicitly, because I'd not be chasing evidence down myself.

And eventually, if it's a significant amount of unsafe or non-trivial code I mdcat itself, then you'd really need to convince me to review it, to add that amount of code for a terminal I don't use myself, and an image format I find terrible.

And you'd probably also need to step in for long term maintenance of that part.

**Comment by swsnr** [comment]
PS: In case you're asking about libsixel: It qualifies for pretty much none of the above criteria.  As far as I'm aware it has no automated test, let alone fuzzing.

**Comment by VarLad** [comment]
@swsnr I was talking about [Chafa](https://github.com/hpjansson/chafa) but I guess you don't mean that either.

**Comment by VarLad** [comment]
Looking into it a bit more, looks like there's a pure Rust library, which implements all the 3 protocols (Sixels, Kitty, ITerm2, and halfblocks as fallback) while not depending on libsixel :) 
https://github.com/benjajaja/ratatui-image

**Comment by swsnr** [comment]
I do not know about Chafa :shrug: As said above, you'd need to find that out.

A pure Rust implementation wouldn't change much.  I'd still expect a well-established crate and good test coverage.  Fuzzying and safety audit too, if the crate has a decent amount of unsafe code.  Same goes for all dependencies of that crate, and there shouldn't be too many of those.

So ratatui-image is likely not an option.  A few clicks from its crates.io page got me to https://github.com/mkrueger/icy_sixel which like its original art has no automated tests at all and appears to barely maintained at best.
