### ISSUE TITLE
Fail to compile on ARM 32 bit musl platforms

### ISSUE THREAD

**Issue by FollieHiyuki** [swsnr/mdcat#219]
Happens on AlpineLinux CI:
- https://gitlab.alpinelinux.org/FollieHiyuki/aports/-/jobs/922939
- https://gitlab.alpinelinux.org/FollieHiyuki/aports/-/jobs/922938

I lack the knowledge to know why, so I opened this issue.

**Comment by swsnr** [comment]
I'm sorry but I don't use ARM devices, so I can't really fix this and don't really care to be honest.

I'll happily review a pull request which fixes this ( and ideally adds CI so I don't break it accidentally 😇) but I won't fix this myself, so I'm closing this issue because it's not actionable for me 🙂

**Comment by swsnr** [comment]
@FollieHiyuki You might want to look into the transitive ring dependency.  I didn't check the logs you linked (too lengthy 😬 ), but ring is the only dependency in mdcat's tree which can cause architecture-dependent build failures.

If ring doesn't support the architecture you may want to try building the ureq dependency with `default-features=false` and explicit `gzip` and `native-tls` features to enable the native (i.e. openssl) TLS backend which doesn't use ring.  I think you need to enable the native connector explicitly in `src/resources.rs` too, as far as I remember.

I'd happily review a pull request which adds a `native-tls` feature to `mdcat` as well, as long as the default build setup still uses rustls in order to simplify compilation on mainstream architectures (no openssl headers required) and support static linking.

**Comment by FollieHiyuki** [comment]
You can ignore most of the log :v:

The actual error is here:
```
...
   Compiling ring v0.16.20
   Compiling rayon v1.6.0
   Compiling is-terminal v0.4.1
   Compiling bincode v1.3.3
   Compiling jpeg-decoder v0.3.0
   Compiling tiff v0.8.0
   Compiling webpki v0.22.0
   Compiling sct v0.7.0
   Compiling webpki-roots v0.22.5
   Compiling clap_derive v4.0.21
   Compiling pin-project-internal v1.0.12
   Compiling tracing-attributes v0.1.23
   Compiling thiserror-impl v1.0.37
   Compiling ureq v2.5.0
   Compiling pin-project v1.0.12
   Compiling flume v0.10.14
   Compiling exr v1.5.2
   Compiling tracing v0.1.37
   Compiling tracing-subscriber v0.3.16
   Compiling clap v4.0.29
   Compiling syntect v5.0.0
   Compiling clap_complete v4.0.6
   Compiling image v0.24.5
   Compiling mdcat v0.30.3 (/builds/FollieHiyuki/aports/testing/mdcat/src/mdcat-mdcat-0.30.3)
error: Undefined temporary symbol .LBB17_2
error: could not compile `mdcat` due to previous error
```

I'm not a Rust developer, so can you guide me on what to patch in `src/resources.rs` file? I don't mind carry a simple patch downstream forever.

**Comment by swsnr** [comment]
#220 enables native-tls 🙂   Please feel free to carry the corresponding patch downstream 🙂

**Comment by FollieHiyuki** [comment]
Thanks for the patch. In the latest CI `mdcat` is linked against system OpenSSL as expected.

The builds for 32-bit ARM platforms still fail though, sadly. It might be because of the tool chain, and not `mdcat`'s fault I think.

**Comment by swsnr** [comment]
I'm afraid I can't help you any better. You may want to ask the Rust community for help here 🙂

**Comment by swsnr** [comment]
@FollieHiyuki Just a small follow up: With #229 mdcat will use a different HTTP library which brings a bunch of different dependencies, which could fix those builds.

If those ARM 32 build still fail please do feel free to send me the build logs (I'd appreciate the relevant excerpt instead of a link to some CI platform 😇 ) and I might be able to help 🙂

**Comment by FollieHiyuki** [comment]
Thanks for all the hard work. I decided to temporarily disable 32-bit ARM builds on AlpineLinux and deal with them later. The switch to `reqwest` is nice since I don't have to carry patches downstream anymore.
