### ISSUE TITLE
`cargo install mdcat` doesn’t install manpage

### ISSUE THREAD

**Issue by treyharris** [swsnr/mdcat#221]
I tested this on a clean machine with a brand-new Rustup install. If you do `cargo install mdcat` and run `mdcat --help`, you get

```
[…]
See 'man 1 mdcat' for more information.
```

however, the manual page is not installed. And checking the `$HOME/.cargo` directory recursively, the only version remains in the package cache as `mdcat.1.adoc`.

I tried starting over and re-installing each time after creating:

- `~/.cargo/man`
- `~/.cargo/man/man1`
- `~/.cargo/share`
- `~/.cargo/share/man`
- `~/.cargo/share/man/man1`

and none of those worked, either. I don’t know Rust so I don’t know how to read the configuration, but I suspect there’s just a line of configuration missing somewhere.

Thanks—this is a great tool!

**Comment by treyharris** [comment]
Oh—and a suggestion I’ve seen other single-executable programs implement for dealing with when manpage installation isn’t reliable: a `--man` option that just outputs the formatted manual on stdout.

Of course, just installing the manual in the firs place is the “right” thing to do, but I’m just mentioning that this is an option some programs—especially ones that don’t install into the global OS but just the user’s local storage, since customizing `MANPATH` is rarely done—have used as well.

**Comment by swsnr** [comment]
You're not missing anything; cargo simply doesn't support data files (completions are missing for the same reason). There'll never be anything in any of the paths you mentioned.

You'll need to install additional data files yourself, by placing the manpage in `~/.local/share/man` (which is part of manpath by default, at least on my system).

Thank you for your suggestion, but I don't think I'll not add it.  The manpage is included in the precompiled releases you can download from Github, which get build on Github in a controlled environment; including it in the build itself is challenging because the manpage requires Ruby and asciidoctor (i.e. an entirely different toolchain) to build.  Requiring this for every build would make installation more complicated.

I recommend to use the prebuilt binaries, and install the extra files manually. Or try to get mdcat added to whatever distribution you use :)

**Comment by treyharris** [comment]
> I recommend to use the prebuilt binaries, and install the extra files manually. Or try to get mdcat added to whatever distribution you use :)

I use Ubuntu—do you happen to know how to ask them without a support contract? I see a general email address so I could try that, but it feels like there’s probably a process. Thanks!

**Comment by swsnr** [comment]
I do not know.  But you can create your own PPA and package mdcat yourself 🙂
