### ISSUE TITLE
Starting a Kitty terminal from an ITerm2 terminal causes mdcat to detect iterm2 instead of kitty

### ISSUE THREAD

**Issue by norman-abramovitz** [swsnr/mdcat#230]
Starting a kitty terminal from an iterm2 terminal causes mdcat not to detect the kitty correctly.

From the Iterm2 terminal session

> $ mdcat --version
> mdcat 0.28.0
> $ mdcat --detect-only
> Terminal: iTerm2
> $ echo TERM=$TERM TERM_PROGRAM=$TERM_PROGRAM
> TERM=xterm-256color TERM_PROGRAM=iTerm.app
> $ kitty &

From the kitty terminal session

> $ mdcat --detect-only
> Terminal: iTerm2
> $ echo TERM=$TERM TERM_PROGRAM=$TERM_PROGRAM
> TERM=xterm-kitty TERM_PROGRAM=iTerm.app

Unsetting the environment variable $TERM_PROGRAM makes the mdcat detect the kitty terminal correctly.

> $ unset TERM_PROGRAM
> $ mdcat --detect-only                       
> Terminal: Kitty

**Comment by swsnr** [comment]
> Starting a kitty terminal from an iterm2 terminal causes mdcat not to detect the kitty correctly.

Well, this leaks environment variables from iterm2 down to kitty; no wonder this spoils terminal detection.  In a way that's even documented; see the manpage which documents which environment variables mdcat looks at and in which order.

I don't think we can fix this; if we changed the order of environment variables we just break different combinations of this 🤷🏿 

If you've got an idea how to fix this solid, I welcome a pull request but meanwhile I tend to close this as won't fix, because there's only so much mdcat can do if environment variables of different terminals get mixed up.

**Comment by norman-abramovitz** [comment]
Maybe report a warning since there is an inconsistency between TERM and TERM_PROGRAM?

Since TERM has the word kitty in it, the variable TERM_PROGRAM should be ignored.  My understanding of TERM_PROGRAM is that it is additional information, so if TERM has sufficient information, then we do not need to look at TERM_PROGRAM.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.term

Nothing solid, but I will  look around to see if there are better ways.

**Comment by swsnr** [comment]
I think we could always check `TERM` first, because every terminal emulator is probably supposed to set it explicitly, meaning it's much less likely to leak.

I'll refactor terminal detection to make this easier to implement and hopefully solve this issue.

**Comment by swsnr** [comment]
@norman-abramovitz You may want to test #232; it should fix this issue.
