### ISSUE TITLE
Allow arguments to be repeated

### ISSUE THREAD

**Issue by petdance** [swsnr/mdcat#277]
I'd like it if `mdcat` didn't fail if `-p` is specified twice.

I've got `alias mdcat='mdcat -p'` but sometimes I still add `-p` out of habit, and mdcat fails with `error: The argument '--paginate' was provided more than once, but cannot be used multiple times`.  This has come up when I'm demoing `mdcat` to coworkers and want to explain how the `-p` obviates piping through `less`.

I think it makes sense to allow redundant options if they don't conflict. For example, I can `grep -i -i foo *` and it's not a problem.

**Comment by swsnr** [comment]
Yeah I guess this makes sense.  You wouldn't happen to feel inclined to make a pull request for this, would you?

Otherwise, I'm afraid it'll take me some time for me to find motivation to change this, for it's a rather boring thing and doesn't look like much fun 😬

**Comment by petdance** [comment]
I will see what I can do!  I haven't touched Rust in years so this will be an adventure.

**Comment by swsnr** [comment]
👍🏿  

Incidentally, I forgot to point out that `mdcat` uses a pager by default if invoked as `mdless`, so instead of your `mdcat -p` alias you can also link `mdcat` to `mdless` and use `mdless` to get paging.  See https://github.com/swsnr/mdcat/blob/main/mdcat.1.adoc#description

I've pushed a small change which documents this in README as well.

**Comment by swsnr** [comment]
@petdance I've pushed another change to mention mdless in `--help`.

If `mdless` fixes your issue I'll close this ticket, because realistically, I don't have motivation to fix it.

As always however, pull requests are always welcome 🙂
